namespace IOCv2.Application.Features.StudentTerms.Commands.AddStudentManual;

public record AddStudentManualResponse
{
    public Guid StudentTermId { get; init; }
    /// <summary>
    /// Temporary password generated by the system. Admin must distribute this to the student out-of-band.
    /// Returned once and not stored in plaintext.
    /// </summary>
    public string TemporaryPassword { get; init; } = string.Empty;
}
