services:
  db:
    image: postgres:alpine
    container_name: iocv2_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456@
      POSTGRES_DB: IOCV2Db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - iocv2-network

  backend:
    build:
      context: .
      dockerfile: IOCv2.API/Dockerfile
    container_name: iocv2_backend
    restart: always
    depends_on:
      - db
      - redis
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=IOCV2Db;Username=postgres;Password=123456@
      - Jwt__SecretKey=IOCv2-SuperSecretKey-2024-MinLength-32Characters-Required-For-Security
      - Jwt__Issuer=IOCv2_Server
      - Jwt__Audience=IOCv2_Client
      - ConnectionStrings__Redis=redis:6379
      - Redis__ConnectionString=redis:6379
      - Redis__InstanceName=IOCv2Cache
      - EMAIL_SMTP_HOST=smtp.gmail.com
      - EMAIL_SMTP_PORT=587
      - EMAIL_SENDER_EMAIL=iocv2.noreply@gmail.com
      - EMAIL_SENDER_NAME=IOCv2
      - EMAIL_APP_PASSWORD=zdmtalaxyyyaodib
      - JWT_ACCESS_TOKEN_EXPIRES_IN_MINUTE=60
      - JWT_REFRESH_TOKEN_EXPIRES_IN_DAYS=7
    ports:
      - "8080:8080"
      - "5000:8080"
    networks:
      - iocv2-network

  redis:
    image: redis:alpine
    container_name: iocv2_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - iocv2-network
    command: redis-server --appendonly yes
  # frontend:
  #   build:
  #     context: ./IOCv2_FE
  #     dockerfile: Dockerfile
  #   container_name: iocv2_frontend
  #   depends_on:
  #     - backend
  #   environment:
  #     # URL Backend cho Next.js rewrite/proxy
  #     - API_URL=http://backend:8080
  #     # URL Backend khi gọi trực tiếp từ Browser
  #     - NEXT_PUBLIC_API_URL=http://localhost:8080
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - iocv2-network

volumes:
  postgres_data:
  redis_data:


networks:
  iocv2-network:
    driver: bridge
