//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOCv2.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IOCv2.Application.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản đã được tạo thành công nhưng email thông báo không được gửi. Vui lòng thông báo trực tiếp cho người dùng. Mã: {0}, Mật khẩu: {1}.
        /// </summary>
        internal static string AccountCreatedButEmailFailed {
            get {
                return ResourceManager.GetString("AccountCreatedButEmailFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản đã được tạo thành công.
        /// </summary>
        internal static string AccountCreatedSuccessfully {
            get {
                return ResourceManager.GetString("AccountCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập thành công.
        /// </summary>
        internal static string Auth_LoginSuccess {
            get {
                return ResourceManager.GetString("Auth.LoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng xuất thành công.
        /// </summary>
        internal static string Auth_LogoutSuccess {
            get {
                return ResourceManager.GetString("Auth.LogoutSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu đã được thay đổi thành công..
        /// </summary>
        internal static string Auth_PasswordChangedSuccess {
            get {
                return ResourceManager.GetString("Auth.PasswordChangedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nếu tài khoản hợp lệ, hệ thống sẽ gửi link reset mật khẩu qua email..
        /// </summary>
        internal static string Auth_PasswordResetGenericMessage {
            get {
                return ResourceManager.GetString("Auth.PasswordResetGenericMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link reset mật khẩu đã được gửi vào email của bạn..
        /// </summary>
        internal static string Auth_PasswordResetLinkSent {
            get {
                return ResourceManager.GetString("Auth.PasswordResetLinkSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu đã được reset thành công..
        /// </summary>
        internal static string Auth_PasswordResetSuccess {
            get {
                return ResourceManager.GetString("Auth.PasswordResetSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không thể cho người khác thành quản lí.
        /// </summary>
        internal static string CannotPromoteToManager {
            get {
                return ResourceManager.GetString("CannotPromoteToManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không có quyền xóa doanh nghiệp này..
        /// </summary>
        internal static string Enterprise_DeletePermissionDenied {
            get {
                return ResourceManager.GetString("Enterprise.DeletePermissionDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không có quyền xem thông tin doanh nghiệp này..
        /// </summary>
        internal static string Enterprise_GetByIDPermissionsNotAllowed {
            get {
                return ResourceManager.GetString("Enterprise.GetByIDPermissionsNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doanh nghiệp chưa bị xóa nên không thể khôi phục..
        /// </summary>
        internal static string Enterprise_NotDeleted {
            get {
                return ResourceManager.GetString("Enterprise.NotDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to getByHR_enterprise_attempt:{0}.
        /// </summary>
        internal static string Enterprise_RateLimitGetByHRAttempt {
            get {
                return ResourceManager.GetString("Enterprise.RateLimitGetByHRAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to getByID_enterprise_attempt:{0}.
        /// </summary>
        internal static string Enterprise_RateLimitGetByIDAttempt {
            get {
                return ResourceManager.GetString("Enterprise.RateLimitGetByIDAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to getEnterprises_enterprise_attempt:{0}.
        /// </summary>
        internal static string Enterprise_RateLimitGetEnterprisesAttempt {
            get {
                return ResourceManager.GetString("Enterprise.RateLimitGetEnterprisesAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update_enterprise_attempt:{0}.
        /// </summary>
        internal static string Enterprise_RateLimitUpdateAttempt {
            get {
                return ResourceManager.GetString("Enterprise.RateLimitUpdateAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn đã gửi request quá nhiều lần..
        /// </summary>
        internal static string Enterprise_RequestManyTimes {
            get {
                return ResourceManager.GetString("Enterprise.RequestManyTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không có quyền khôi phục doanh nghiệp này..
        /// </summary>
        internal static string Enterprise_RestorePermissionDenied {
            get {
                return ResourceManager.GetString("Enterprise.RestorePermissionDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo Epic thành công..
        /// </summary>
        internal static string Epic_CreatedSuccess {
            get {
                return ResourceManager.GetString("Epic.CreatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa Epic thành công..
        /// </summary>
        internal static string Epic_DeletedSuccess {
            get {
                return ResourceManager.GetString("Epic.DeletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật Epic thành công..
        /// </summary>
        internal static string Epic_UpdatedSuccess {
            get {
                return ResourceManager.GetString("Epic.UpdatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn ứng tuyển đã được chấp nhận thành công..
        /// </summary>
        internal static string InternshipApplication_AcceptSuccess {
            get {
                return ResourceManager.GetString("InternshipApplication.AcceptSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã gán Mentor và thêm sinh viên vào nhóm hiện có thành công..
        /// </summary>
        internal static string InternshipApplication_AssignMentorExistingGroupSuccess {
            get {
                return ResourceManager.GetString("InternshipApplication.AssignMentorExistingGroupSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã gán Mentor và tạo nhóm thực tập mới thành công..
        /// </summary>
        internal static string InternshipApplication_AssignMentorNewGroupSuccess {
            get {
                return ResourceManager.GetString("InternshipApplication.AssignMentorNewGroupSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã gán Mentor thành công..
        /// </summary>
        internal static string InternshipApplication_AssignMentorSuccess {
            get {
                return ResourceManager.GetString("InternshipApplication.AssignMentorSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã gán dự án vào nhóm thực tập thành công..
        /// </summary>
        internal static string InternshipApplication_AssignProjectSuccess {
            get {
                return ResourceManager.GetString("InternshipApplication.AssignProjectSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn ứng tuyển đã bị từ chối..
        /// </summary>
        internal static string InternshipApplication_RejectSuccess {
            get {
                return ResourceManager.GetString("InternshipApplication.RejectSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu trữ nhóm thành công..
        /// </summary>
        internal static string InternshipGroup_ArchiveSuccess {
            get {
                return ResourceManager.GetString("InternshipGroup.ArchiveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã thêm thành công {Count} sinh viên vào nhóm: {InternshipId}.
        /// </summary>
        internal static string InternshipGroup_LogAddedStudentsSuccess {
            get {
                return ResourceManager.GetString("InternshipGroup.LogAddedStudentsSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang thêm sinh viên vào nhóm: {InternshipId}.
        /// </summary>
        internal static string InternshipGroup_LogAddingStudents {
            get {
                return ResourceManager.GetString("InternshipGroup.LogAddingStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo nhóm thực tập thành công: {InternshipId}.
        /// </summary>
        internal static string InternshipGroup_LogCreatedSuccess {
            get {
                return ResourceManager.GetString("InternshipGroup.LogCreatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang tạo nhóm thực tập mới: {GroupName} cho kỳ: {TermId}.
        /// </summary>
        internal static string InternshipGroup_LogCreating {
            get {
                return ResourceManager.GetString("InternshipGroup.LogCreating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa nhóm thực tập thành công: {InternshipId}.
        /// </summary>
        internal static string InternshipGroup_LogDeletedSuccess {
            get {
                return ResourceManager.GetString("InternshipGroup.LogDeletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang xóa nhóm thực tập: {InternshipId}.
        /// </summary>
        internal static string InternshipGroup_LogDeleting {
            get {
                return ResourceManager.GetString("InternshipGroup.LogDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã xóa thành công sinh viên khỏi nhóm: {InternshipId}.
        /// </summary>
        internal static string InternshipGroup_LogRemovedStudentsSuccess {
            get {
                return ResourceManager.GetString("InternshipGroup.LogRemovedStudentsSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang xóa sinh viên khỏi nhóm: {InternshipId}.
        /// </summary>
        internal static string InternshipGroup_LogRemovingStudents {
            get {
                return ResourceManager.GetString("InternshipGroup.LogRemovingStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật nhóm thực tập thành công: {InternshipId}.
        /// </summary>
        internal static string InternshipGroup_LogUpdatedSuccess {
            get {
                return ResourceManager.GetString("InternshipGroup.LogUpdatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang cập nhật nhóm thực tập: {InternshipId}.
        /// </summary>
        internal static string InternshipGroup_LogUpdating {
            get {
                return ResourceManager.GetString("InternshipGroup.LogUpdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyển sinh viên thành công..
        /// </summary>
        internal static string InternshipGroup_MoveSuccess {
            get {
                return ResourceManager.GetString("InternshipGroup.MoveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể xóa đợt thực tập &apos;{0}&apos; vì hiện có {1} nhóm thực tập đang hoạt động (Active). Vui lòng kết thúc hoặc lưu trữ tất cả nhóm trước khi thực hiện xóa..
        /// </summary>
        internal static string InternshipPhase_CannotDeleteHasActiveGroups {
            get {
                return ResourceManager.GetString("InternshipPhase.CannotDeleteHasActiveGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể xóa đợt thực tập &apos;{0}&apos; vì đợt đang ở trạng thái Đang thực tập (InProgress). Vui lòng đóng đợt thực tập trước khi xóa..
        /// </summary>
        internal static string InternshipPhase_CannotDeleteInProgress {
            get {
                return ResourceManager.GetString("InternshipPhase.CannotDeleteInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể cập nhật đợt thực tập &apos;{0}&apos; vì đợt này đã ở trạng thái Đã đóng (Closed). Chỉ có thể chỉnh sửa đợt thực tập đang ở trạng thái Nháp (Draft) hoặc Đang mở (Open)..
        /// </summary>
        internal static string InternshipPhase_CannotUpdateClosed {
            get {
                return ResourceManager.GetString("InternshipPhase.CannotUpdateClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo đợt thực tập thành công..
        /// </summary>
        internal static string InternshipPhase_CreateSuccess {
            get {
                return ResourceManager.GetString("InternshipPhase.CreateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa đợt thực tập thành công..
        /// </summary>
        internal static string InternshipPhase_DeleteSuccess {
            get {
                return ResourceManager.GetString("InternshipPhase.DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả đợt thực tập không được vượt quá 2000 ký tự..
        /// </summary>
        internal static string InternshipPhase_DescriptionMaxLength {
            get {
                return ResourceManager.GetString("InternshipPhase.DescriptionMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đợt thực tập có tên &apos;{0}&apos; đã tồn tại trong doanh nghiệp này. Vui lòng chọn một tên khác..
        /// </summary>
        internal static string InternshipPhase_DuplicateName {
            get {
                return ResourceManager.GetString("InternshipPhase.DuplicateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể đổi tên thành &apos;{0}&apos; vì đã có đợt thực tập khác trong doanh nghiệp này sử dụng tên này..
        /// </summary>
        internal static string InternshipPhase_DuplicateNameOnUpdate {
            get {
                return ResourceManager.GetString("InternshipPhase.DuplicateNameOnUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày kết thúc phải sau ngày bắt đầu..
        /// </summary>
        internal static string InternshipPhase_EndDateAfterStartDate {
            get {
                return ResourceManager.GetString("InternshipPhase.EndDateAfterStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể đặt ngày kết thúc trong quá khứ cho đợt thực tập &apos;{0}&apos; đang ở trạng thái Open hoặc InProgress..
        /// </summary>
        internal static string InternshipPhase_EndDateInPastForActivePhase {
            get {
                return ResourceManager.GetString("InternshipPhase.EndDateInPastForActivePhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày kết thúc (EndDate) không được để trống..
        /// </summary>
        internal static string InternshipPhase_EndDateRequired {
            get {
                return ResourceManager.GetString("InternshipPhase.EndDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID doanh nghiệp (EnterpriseId) không được để trống..
        /// </summary>
        internal static string InternshipPhase_EnterpriseIdRequired {
            get {
                return ResourceManager.GetString("InternshipPhase.EnterpriseIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy thông tin nhân viên doanh nghiệp cho tài khoản hiện tại..
        /// </summary>
        internal static string InternshipPhase_EnterpriseUserNotFound {
            get {
                return ResourceManager.GetString("InternshipPhase.EnterpriseUserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể chuyển trạng thái từ &apos;{0}&apos; sang &apos;{1}&apos;. Vui lòng kiểm tra lại quy trình trạng thái..
        /// </summary>
        internal static string InternshipPhase_InvalidStatusTransition {
            get {
                return ResourceManager.GetString("InternshipPhase.InvalidStatusTransition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trả về thông tin đợt thực tập {0} từ cache..
        /// </summary>
        internal static string InternshipPhase_Log_ByIdFromCache {
            get {
                return ResourceManager.GetString("InternshipPhase.Log.ByIdFromCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy đợt thực tập với ID {0}..
        /// </summary>
        internal static string InternshipPhase_Log_ByIdNotFound {
            get {
                return ResourceManager.GetString("InternshipPhase.Log.ByIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lấy thông tin đợt thực tập thành công — PhaseId: {0}, Tên: &apos;{1}&apos;, Doanh nghiệp: &apos;{2}&apos;, Trạng thái: {3}, Số nhóm: {4}..
        /// </summary>
        internal static string InternshipPhase_Log_ByIdSuccess {
            get {
                return ResourceManager.GetString("InternshipPhase.Log.ByIdSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi khi tạo đợt thực tập &apos;{0}&apos; cho doanh nghiệp {1}. Đã rollback transaction..
        /// </summary>
        internal static string InternshipPhase_Log_CreateError {
            get {
                return ResourceManager.GetString("InternshipPhase.Log.CreateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo đợt thực tập thành công — PhaseId: {0}, Tên: &apos;{1}&apos;, Doanh nghiệp: {2}..
        /// </summary>
        internal static string InternshipPhase_Log_CreateSuccess {
            get {
                return ResourceManager.GetString("InternshipPhase.Log.CreateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bắt đầu tạo đợt thực tập &apos;{0}&apos; cho doanh nghiệp {1}..
        /// </summary>
        internal static string InternshipPhase_Log_Creating {
            get {
                return ResourceManager.GetString("InternshipPhase.Log.Creating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi khi xóa đợt thực tập {0}. Đã rollback transaction..
        /// </summary>
        internal static string InternshipPhase_Log_DeleteError {
            get {
                return ResourceManager.GetString("InternshipPhase.Log.DeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ chối xóa đợt thực tập &apos;{0}&apos; (ID: {1}) — hiện có {2} nhóm thực tập đang hoạt động..
        /// </summary>
        internal static string InternshipPhase_Log_DeleteHasActiveGroups {
            get {
                return ResourceManager.GetString("InternshipPhase.Log.DeleteHasActiveGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ chối xóa đợt thực tập &apos;{0}&apos; (ID: {1}) — đợt đang ở trạng thái InProgress và không thể xóa..
        /// </summary>
        internal static string InternshipPhase_Log_DeleteInProgress {
            get {
                return ResourceManager.GetString("InternshipPhase.Log.DeleteInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có bản ghi nào được lưu khi xóa đợt thực tập {0}. Đã rollback transaction..
        /// </summary>
        internal static string InternshipPhase_Log_DeleteNoChanges {
            get {
                return ResourceManager.GetString("InternshipPhase.Log.DeleteNoChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy đợt thực tập với ID {0}. Yêu cầu xóa bị từ chối..
        /// </summary>
        internal static string InternshipPhase_Log_DeleteNotFound {
            get {
                return ResourceManager.GetString("InternshipPhase.Log.DeleteNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa đợt thực tập thành công — PhaseId: {0}, Tên: &apos;{1}&apos;, Doanh nghiệp: {2}..
        /// </summary>
        internal static string InternshipPhase_Log_DeleteSuccess {
            get {
                return ResourceManager.GetString("InternshipPhase.Log.DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bắt đầu xóa đợt thực tập {0}..
        /// </summary>
        internal static string InternshipPhase_Log_Deleting {
            get {
                return ResourceManager.GetString("InternshipPhase.Log.Deleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đợt thực tập có tên &apos;{0}&apos; đã tồn tại trong doanh nghiệp {1}. Từ chối tạo mới..
        /// </summary>
        internal static string InternshipPhase_Log_DuplicateName {
            get {
                return ResourceManager.GetString("InternshipPhase.Log.DuplicateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy doanh nghiệp có ID {0}. Không thể tạo đợt thực tập..
        /// </summary>
        internal static string InternshipPhase_Log_EnterpriseNotFound {
            get {
                return ResourceManager.GetString("InternshipPhase.Log.EnterpriseNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lấy thông tin chi tiết đợt thực tập {0}..
        /// </summary>
        internal static string InternshipPhase_Log_GettingById {
            get {
                return ResourceManager.GetString("InternshipPhase.Log.GettingById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lấy danh sách đợt thực tập cho doanh nghiệp {0} — lọc trạng thái: {1}, trang: {2}..
        /// </summary>
        internal static string InternshipPhase_Log_GettingList {
            get {
                return ResourceManager.GetString("InternshipPhase.Log.GettingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lấy danh sách đợt thực tập của sinh viên (UserId: {0})..
        /// </summary>
        internal static string InternshipPhase_Log_GettingMyPhases {
            get {
                return ResourceManager.GetString("InternshipPhase.Log.GettingMyPhases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ chối chuyển trạng thái đợt thực tập {0} từ &apos;{1}&apos; sang &apos;{2}&apos; — không hợp lệ..
        /// </summary>
        internal static string InternshipPhase_Log_InvalidStatusTransition {
            get {
                return ResourceManager.GetString("InternshipPhase.Log.InvalidStatusTransition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trả về danh sách đợt thực tập từ cache cho doanh nghiệp {0}..
        /// </summary>
        internal static string InternshipPhase_Log_ListFromCache {
            get {
                return ResourceManager.GetString("InternshipPhase.Log.ListFromCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lấy danh sách đợt thực tập thành công cho doanh nghiệp {0} — trả về {1}/{2} bản ghi (trang {3})..
        /// </summary>
        internal static string InternshipPhase_Log_ListSuccess {
            get {
                return ResourceManager.GetString("InternshipPhase.Log.ListSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lấy danh sách đợt thực tập thành công cho sinh viên {0} (UserId: {1}) — tìm thấy {2} đợt thực tập..
        /// </summary>
        internal static string InternshipPhase_Log_MyPhasesSuccess {
            get {
                return ResourceManager.GetString("InternshipPhase.Log.MyPhasesSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ chối truy cập — User {0} cố thao tác trên doanh nghiệp {1} nhưng thuộc doanh nghiệp {2}..
        /// </summary>
        internal static string InternshipPhase_Log_OwnershipDenied {
            get {
                return ResourceManager.GetString("InternshipPhase.Log.OwnershipDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy hồ sơ sinh viên cho UserId {0}. Yêu cầu bị từ chối..
        /// </summary>
        internal static string InternshipPhase_Log_StudentNotFound {
            get {
                return ResourceManager.GetString("InternshipPhase.Log.StudentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ chối cập nhật đợt thực tập &apos;{0}&apos; (ID: {1}) — đợt đang ở trạng thái Đã đóng (Closed)..
        /// </summary>
        internal static string InternshipPhase_Log_UpdateClosed {
            get {
                return ResourceManager.GetString("InternshipPhase.Log.UpdateClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ chối cập nhật đợt thực tập {0} — tên &apos;{1}&apos; đã được sử dụng bởi đợt thực tập khác trong doanh nghiệp {2}..
        /// </summary>
        internal static string InternshipPhase_Log_UpdateDuplicateName {
            get {
                return ResourceManager.GetString("InternshipPhase.Log.UpdateDuplicateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi khi cập nhật đợt thực tập {0}. Đã rollback transaction..
        /// </summary>
        internal static string InternshipPhase_Log_UpdateError {
            get {
                return ResourceManager.GetString("InternshipPhase.Log.UpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có bản ghi nào được lưu khi cập nhật đợt thực tập {0}. Đã rollback transaction..
        /// </summary>
        internal static string InternshipPhase_Log_UpdateNoChanges {
            get {
                return ResourceManager.GetString("InternshipPhase.Log.UpdateNoChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy đợt thực tập với ID {0}. Yêu cầu cập nhật bị từ chối..
        /// </summary>
        internal static string InternshipPhase_Log_UpdateNotFound {
            get {
                return ResourceManager.GetString("InternshipPhase.Log.UpdateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật đợt thực tập thành công — PhaseId: {0}, Tên: &apos;{1}&apos;..
        /// </summary>
        internal static string InternshipPhase_Log_UpdateSuccess {
            get {
                return ResourceManager.GetString("InternshipPhase.Log.UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bắt đầu cập nhật đợt thực tập {0} — tên mới: &apos;{1}&apos;, trạng thái mới: {2}..
        /// </summary>
        internal static string InternshipPhase_Log_Updating {
            get {
                return ResourceManager.GetString("InternshipPhase.Log.Updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng sinh viên tối đa (MaxStudents) phải lớn hơn 0..
        /// </summary>
        internal static string InternshipPhase_MaxStudentsGreaterThanZero {
            get {
                return ResourceManager.GetString("InternshipPhase.MaxStudentsGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đợt thực tập không được vượt quá 255 ký tự..
        /// </summary>
        internal static string InternshipPhase_NameMaxLength {
            get {
                return ResourceManager.GetString("InternshipPhase.NameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đợt thực tập không được để trống..
        /// </summary>
        internal static string InternshipPhase_NameRequired {
            get {
                return ResourceManager.GetString("InternshipPhase.NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy đợt thực tập..
        /// </summary>
        internal static string InternshipPhase_NotFound {
            get {
                return ResourceManager.GetString("InternshipPhase.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không có quyền thao tác trên đợt thực tập của doanh nghiệp này..
        /// </summary>
        internal static string InternshipPhase_NotYourEnterprise {
            get {
                return ResourceManager.GetString("InternshipPhase.NotYourEnterprise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số trang phải lớn hơn hoặc bằng 1..
        /// </summary>
        internal static string InternshipPhase_PageNumberMinValue {
            get {
                return ResourceManager.GetString("InternshipPhase.PageNumberMinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kích thước trang phải từ 1 đến 50..
        /// </summary>
        internal static string InternshipPhase_PageSizeRange {
            get {
                return ResourceManager.GetString("InternshipPhase.PageSizeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID đợt thực tập (PhaseId) không được để trống..
        /// </summary>
        internal static string InternshipPhase_PhaseIdRequired {
            get {
                return ResourceManager.GetString("InternshipPhase.PhaseIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày bắt đầu không được là ngày trong quá khứ..
        /// </summary>
        internal static string InternshipPhase_StartDateNotInPast {
            get {
                return ResourceManager.GetString("InternshipPhase.StartDateNotInPast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày bắt đầu (StartDate) không được để trống..
        /// </summary>
        internal static string InternshipPhase_StartDateRequired {
            get {
                return ResourceManager.GetString("InternshipPhase.StartDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái đợt thực tập không hợp lệ..
        /// </summary>
        internal static string InternshipPhase_StatusInvalid {
            get {
                return ResourceManager.GetString("InternshipPhase.StatusInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy hồ sơ sinh viên cho tài khoản hiện tại..
        /// </summary>
        internal static string InternshipPhase_StudentNotFound {
            get {
                return ResourceManager.GetString("InternshipPhase.StudentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có thay đổi nào được lưu cho đợt thực tập..
        /// </summary>
        internal static string InternshipPhase_UpdateNoChanges {
            get {
                return ResourceManager.GetString("InternshipPhase.UpdateNoChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật đợt thực tập thành công..
        /// </summary>
        internal static string InternshipPhase_UpdateSuccess {
            get {
                return ResourceManager.GetString("InternshipPhase.UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo issue thành công..
        /// </summary>
        internal static string Issue_CreateSuccess {
            get {
                return ResourceManager.GetString("Issue.CreateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa issue thành công..
        /// </summary>
        internal static string Issue_DeleteSuccess {
            get {
                return ResourceManager.GetString("Issue.DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật trạng thái issue thành công..
        /// </summary>
        internal static string Issue_UpdateStatusSuccess {
            get {
                return ResourceManager.GetString("Issue.UpdateStatusSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vị trí mới phải khác vị trí hiện tại.
        /// </summary>
        internal static string NewRoleMustBeDifferent {
            get {
                return ResourceManager.GetString("NewRoleMustBeDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page number must be greater than or equal to 1.
        /// </summary>
        internal static string PageNumber_MinValue {
            get {
                return ResourceManager.GetString("PageNumber.MinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page size must not exceed 100.
        /// </summary>
        internal static string PageSize_MaxValue {
            get {
                return ResourceManager.GetString("PageSize.MaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page size must be greater than or equal to 1.
        /// </summary>
        internal static string PageSize_MinValue {
            get {
                return ResourceManager.GetString("PageSize.MinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thông tin thành công..
        /// </summary>
        internal static string Profile_UpdateSuccess {
            get {
                return ResourceManager.GetString("Profile.UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã truy xuất thành công {Count} tài nguyên dự án.
        /// </summary>
        internal static string ProjectResources_GetAllSuccess {
            get {
                return ResourceManager.GetString("ProjectResources.GetAllSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã truy xuất thành công tài nguyên dự án: {ResourceId}.
        /// </summary>
        internal static string ProjectResources_GetByIdSuccess {
            get {
                return ResourceManager.GetString("ProjectResources.GetByIdSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project resource with ID {ResourceId} deleted successfully..
        /// </summary>
        internal static string ProjectResources_LogDeleteSuccess {
            get {
                return ResourceManager.GetString("ProjectResources.LogDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã tải tệp {FileName} lên dự án {ProjectId}.
        /// </summary>
        internal static string ProjectResources_LogUploadSuccess {
            get {
                return ResourceManager.GetString("ProjectResources.LogUploadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa dự án thành công.
        /// </summary>
        internal static string Projects_DeleteSuccess {
            get {
                return ResourceManager.GetString("Projects.DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã tạo dự án {ProjectId} cho chương trình thực tập {InternshipId}..
        /// </summary>
        internal static string Projects_LogCreateSuccess {
            get {
                return ResourceManager.GetString("Projects.LogCreateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dự án đã bị xóa {ProjectId}.
        /// </summary>
        internal static string Projects_LogDelete {
            get {
                return ResourceManager.GetString("Projects.LogDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully retrieved {Count} projects for internship ID: {InternshipId}.
        /// </summary>
        internal static string Projects_LogGetByInternshipIdSuccess {
            get {
                return ResourceManager.GetString("Projects.LogGetByInternshipIdSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dự án không tìm thấy.
        /// </summary>
        internal static string Projects_NotFound {
            get {
                return ResourceManager.GetString("Projects.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dự án đã được cập nhật {ProjectId}.
        /// </summary>
        internal static string Projects_UpdateSuccess {
            get {
                return ResourceManager.GetString("Projects.UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email thông báo không được gửi. Vui lòng thông báo trực tiếp cho người dùng..
        /// </summary>
        internal static string ResetPassword_StatusNoEmail {
            get {
                return ResourceManager.GetString("ResetPassword.StatusNoEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu đã được reset thành công nhưng email thông báo không được gửi. Vui lòng thông báo trực tiếp cho người dùng. Mật khẩu mới: {0}.
        /// </summary>
        internal static string ResetPassword_SuccessNoEmail {
            get {
                return ResourceManager.GetString("ResetPassword.SuccessNoEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu đã được reset thành công. Email thông báo đã được gửi tới {0}.
        /// </summary>
        internal static string ResetPassword_SuccessWithEmail {
            get {
                return ResourceManager.GetString("ResetPassword.SuccessWithEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role đã được thay đổi thành công nhưng email thông báo không được gửi. Vui lòng thông báo trực tiếp cho người dùng về mã nhân viên mới: {0}.
        /// </summary>
        internal static string RoleChangedButEmailFailed {
            get {
                return ResourceManager.GetString("RoleChangedButEmailFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role đã được thay đổi thành công.
        /// </summary>
        internal static string RoleChangedSuccessfully {
            get {
                return ResourceManager.GetString("RoleChangedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search term cannot exceed 200 characters.
        /// </summary>
        internal static string SearchTerm_MaxLength {
            get {
                return ResourceManager.GetString("SearchTerm.MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort column must be one of: projectname, startdate, enddate, status, createdat.
        /// </summary>
        internal static string SortColumn_AllowedValues {
            get {
                return ResourceManager.GetString("SortColumn.AllowedValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort order must be either &apos;asc&apos; or &apos;desc&apos;.
        /// </summary>
        internal static string SortOrder_AllowedValues {
            get {
                return ResourceManager.GetString("SortOrder.AllowedValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprint đã được hoàn thành thành công. {0} item đã hoàn thành, {1} item đã được di chuyển..
        /// </summary>
        internal static string Sprint_CompletedSuccess {
            get {
                return ResourceManager.GetString("Sprint.CompletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo Sprint thành công..
        /// </summary>
        internal static string Sprint_CreatedSuccess {
            get {
                return ResourceManager.GetString("Sprint.CreatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa Sprint thành công..
        /// </summary>
        internal static string Sprint_DeletedSuccess {
            get {
                return ResourceManager.GetString("Sprint.DeletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bắt đầu Sprint thành công..
        /// </summary>
        internal static string Sprint_StartedSuccess {
            get {
                return ResourceManager.GetString("Sprint.StartedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật Sprint thành công..
        /// </summary>
        internal static string Sprint_UpdatedSuccess {
            get {
                return ResourceManager.GetString("Sprint.UpdatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo stakeholder thành công..
        /// </summary>
        internal static string Stakeholder_CreateSuccess {
            get {
                return ResourceManager.GetString("Stakeholder.CreateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa stakeholder thành công..
        /// </summary>
        internal static string Stakeholder_DeleteSuccess {
            get {
                return ResourceManager.GetString("Stakeholder.DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật stakeholder thành công..
        /// </summary>
        internal static string Stakeholder_UpdateSuccess {
            get {
                return ResourceManager.GetString("Stakeholder.UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy sinh viên này..
        /// </summary>
        internal static string Student_NotFound {
            get {
                return ResourceManager.GetString("Student.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID sinh viên là bắt buộc..
        /// </summary>
        internal static string Student_StudentIdRequired {
            get {
                return ResourceManager.GetString("Student.StudentIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn đã được khôi phục vào đợt thực tập &apos;{0}&apos;..
        /// </summary>
        internal static string StudentTerms_Email_BodyRestore {
            get {
                return ResourceManager.GetString("StudentTerms.Email.BodyRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn đã bị rút khỏi đợt thực tập &apos;{0}&apos;. Vui lòng liên hệ nhà trường nếu có thắc mắc..
        /// </summary>
        internal static string StudentTerms_Email_BodyWithdraw {
            get {
                return ResourceManager.GetString("StudentTerms.Email.BodyWithdraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo khôi phục ghi danh đợt thực tập.
        /// </summary>
        internal static string StudentTerms_Email_SubjectRestore {
            get {
                return ResourceManager.GetString("StudentTerms.Email.SubjectRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo rút khỏi đợt thực tập.
        /// </summary>
        internal static string StudentTerms_Email_SubjectWithdraw {
            get {
                return ResourceManager.GetString("StudentTerms.Email.SubjectWithdraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sinh.
        /// </summary>
        internal static string StudentTerms_Excel_HeaderDateOfBirth {
            get {
                return ResourceManager.GetString("StudentTerms.Excel.HeaderDateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string StudentTerms_Excel_HeaderEmail {
            get {
                return ResourceManager.GetString("StudentTerms.Excel.HeaderEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ và tên.
        /// </summary>
        internal static string StudentTerms_Excel_HeaderFullName {
            get {
                return ResourceManager.GetString("StudentTerms.Excel.HeaderFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyên ngành.
        /// </summary>
        internal static string StudentTerms_Excel_HeaderMajor {
            get {
                return ResourceManager.GetString("StudentTerms.Excel.HeaderMajor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại.
        /// </summary>
        internal static string StudentTerms_Excel_HeaderPhone {
            get {
                return ResourceManager.GetString("StudentTerms.Excel.HeaderPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã sinh viên.
        /// </summary>
        internal static string StudentTerms_Excel_HeaderStudentCode {
            get {
                return ResourceManager.GetString("StudentTerms.Excel.HeaderStudentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu tạm.
        /// </summary>
        internal static string StudentTerms_Excel_HeaderTempPassword {
            get {
                return ResourceManager.GetString("StudentTerms.Excel.HeaderTempPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách sinh viên.
        /// </summary>
        internal static string StudentTerms_Excel_WorksheetStudentList {
            get {
                return ResourceManager.GetString("StudentTerms.Excel.WorksheetStudentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu tạm.
        /// </summary>
        internal static string StudentTerms_Excel_WorksheetTempPassword {
            get {
                return ResourceManager.GetString("StudentTerms.Excel.WorksheetTempPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên kỳ thực tập đã tồn tại, vui lòng chọn tên khác..
        /// </summary>
        internal static string Terms_NameExists {
            get {
                return ResourceManager.GetString("Terms.NameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không xác định được người thực hiện thao tác..
        /// </summary>
        internal static string Users_InvalidAuditor {
            get {
                return ResourceManager.GetString("Users.InvalidAuditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản người dùng hiện tại không còn hoạt động..
        /// </summary>
        internal static string Users_NotActive {
            get {
                return ResourceManager.GetString("Users.NotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy người dùng với mã và role hiện tại..
        /// </summary>
        internal static string Users_NotFound {
            get {
                return ResourceManager.GetString("Users.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã tạo báo cáo vi phạm thành công.
        /// </summary>
        internal static string ViolationReport_CreateViolationReportSuccess {
            get {
                return ResourceManager.GetString("ViolationReport.CreateViolationReportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chỉ có thể xóa báo cáo vi phạm do mình tạo..
        /// </summary>
        internal static string ViolationReport_DeleteNotOwner {
            get {
                return ResourceManager.GetString("ViolationReport.DeleteNotOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả là bắt buộc, không được để trống..
        /// </summary>
        internal static string ViolationReport_DescriptionIsRequired {
            get {
                return ResourceManager.GetString("ViolationReport.DescriptionIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả không được vượt quá {0} ký tự..
        /// </summary>
        internal static string ViolationReport_DescriptionMaxLength {
            get {
                return ResourceManager.GetString("ViolationReport.DescriptionMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả phải có ít nhất {0} ký tự..
        /// </summary>
        internal static string ViolationReport_DescriptionMinLength {
            get {
                return ResourceManager.GetString("ViolationReport.DescriptionMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể cập nhật báo cáo vi phạm {0}..
        /// </summary>
        internal static string ViolationReport_FailedToUpdateViolationReport {
            get {
                return ResourceManager.GetString("ViolationReport.FailedToUpdateViolationReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy báo cáo phù hợp.
        /// </summary>
        internal static string ViolationReport_FilteredNotFound {
            get {
                return ResourceManager.GetString("ViolationReport.FilteredNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kỳ thực tập đã kết thúc..
        /// </summary>
        internal static string ViolationReport_InternshipHasEnded {
            get {
                return ResourceManager.GetString("ViolationReport.InternshipHasEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người hướng dẫn {UserId} đã cố gắng xóa một báo cáo mà họ không sở hữu: {ViolationReportId}.
        /// </summary>
        internal static string ViolationReport_LogDeleteNotOwner {
            get {
                return ResourceManager.GetString("ViolationReport.LogDeleteNotOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy báo cáo vi phạm: {ViolationReportId}.
        /// </summary>
        internal static string ViolationReport_LogNotFound {
            get {
                return ResourceManager.GetString("ViolationReport.LogNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không được phép báo cáo về học sinh này..
        /// </summary>
        internal static string ViolationReport_NotAllowedToReport {
            get {
                return ResourceManager.GetString("ViolationReport.NotAllowedToReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không được phép cập nhật báo cáo này..
        /// </summary>
        internal static string ViolationReport_NotAllowedToUpdateThisReport {
            get {
                return ResourceManager.GetString("ViolationReport.NotAllowedToUpdateThisReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa có báo cáo vi phạm nào..
        /// </summary>
        internal static string ViolationReport_NotFound {
            get {
                return ResourceManager.GetString("ViolationReport.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày xảy ra không được trước ngày bắt đầu thực tập..
        /// </summary>
        internal static string ViolationReport_OccurredDateBeforeInternshipStart {
            get {
                return ResourceManager.GetString("ViolationReport.OccurredDateBeforeInternshipStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chương trình thực tập đã kết thúc..
        /// </summary>
        internal static string ViolationReport_OccurredDateCannotBeAfterInternshipEnd {
            get {
                return ResourceManager.GetString("ViolationReport.OccurredDateCannotBeAfterInternshipEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày xảy ra sự việc không được trước ngày bắt đầu thực tập..
        /// </summary>
        internal static string ViolationReport_OccurredDateCannotBeBeforeInternshipStart {
            get {
                return ResourceManager.GetString("ViolationReport.OccurredDateCannotBeBeforeInternshipStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày xảy ra không được lớn hơn thời điểm hiện tại..
        /// </summary>
        internal static string ViolationReport_OccurredDateInFuture {
            get {
                return ResourceManager.GetString("ViolationReport.OccurredDateInFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày xảy ra sự việc là bắt buộc..
        /// </summary>
        internal static string ViolationReport_OccurredDateIsRequired {
            get {
                return ResourceManager.GetString("ViolationReport.OccurredDateIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang cập nhật báo cáo vi phạm {0} bởi người dùng {1}..
        /// </summary>
        internal static string ViolationReport_UpdatingViolationReportByUser {
            get {
                return ResourceManager.GetString("ViolationReport.UpdatingViolationReportByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người dùng {0} không được phép cập nhật báo cáo vi phạm {1}..
        /// </summary>
        internal static string ViolationReport_UserNotAllowedToUpdateViolationReport {
            get {
                return ResourceManager.GetString("ViolationReport.UserNotAllowedToUpdateViolationReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo cáo vi phạm {0} đã được xóa thành công..
        /// </summary>
        internal static string ViolationReport_ViolationReportDeletedSuccessfully {
            get {
                return ResourceManager.GetString("ViolationReport.ViolationReportDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViolationReportId là bắt buộc..
        /// </summary>
        internal static string ViolationReport_ViolationReportIdIsRequired {
            get {
                return ResourceManager.GetString("ViolationReport.ViolationReportIdIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy báo cáo vi phạm {0}..
        /// </summary>
        internal static string ViolationReport_ViolationReportNotFound {
            get {
                return ResourceManager.GetString("ViolationReport.ViolationReportNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo cáo vi phạm đã được cập nhật bởi người dùng khác vào lúc {0}..
        /// </summary>
        internal static string ViolationReport_ViolationReportUpdatedByAnotherUser {
            get {
                return ResourceManager.GetString("ViolationReport.ViolationReportUpdatedByAnotherUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo cáo đã được cập nhật thành công..
        /// </summary>
        internal static string ViolationReport_ViolationReportUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("ViolationReport.ViolationReportUpdatedSuccessfully", resourceCulture);
            }
        }
    }
}
