//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IOCv2.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IOCv2.Application.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản đã được tạo thành công nhưng email thông báo không được gửi. Vui lòng thông báo trực tiếp cho người dùng. Mã: {0}, Mật khẩu: {1}.
        /// </summary>
        internal static string AccountCreatedButEmailFailed {
            get {
                return ResourceManager.GetString("AccountCreatedButEmailFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản đã được tạo thành công.
        /// </summary>
        internal static string AccountCreatedSuccessfully {
            get {
                return ResourceManager.GetString("AccountCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập thành công.
        /// </summary>
        internal static string Auth_LoginSuccess {
            get {
                return ResourceManager.GetString("Auth.LoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng xuất thành công.
        /// </summary>
        internal static string Auth_LogoutSuccess {
            get {
                return ResourceManager.GetString("Auth.LogoutSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu đã được thay đổi thành công..
        /// </summary>
        internal static string Auth_PasswordChangedSuccess {
            get {
                return ResourceManager.GetString("Auth.PasswordChangedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nếu tài khoản hợp lệ, hệ thống sẽ gửi link reset mật khẩu qua email..
        /// </summary>
        internal static string Auth_PasswordResetGenericMessage {
            get {
                return ResourceManager.GetString("Auth.PasswordResetGenericMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link reset mật khẩu đã được gửi vào email của bạn..
        /// </summary>
        internal static string Auth_PasswordResetLinkSent {
            get {
                return ResourceManager.GetString("Auth.PasswordResetLinkSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu đã được reset thành công..
        /// </summary>
        internal static string Auth_PasswordResetSuccess {
            get {
                return ResourceManager.GetString("Auth.PasswordResetSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không thể cho người khác thành quản lí.
        /// </summary>
        internal static string CannotPromoteToManager {
            get {
                return ResourceManager.GetString("CannotPromoteToManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không có quyền xóa doanh nghiệp này..
        /// </summary>
        internal static string Enterprise_DeletePermissionDenied {
            get {
                return ResourceManager.GetString("Enterprise.DeletePermissionDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không có quyền xem thông tin doanh nghiệp này..
        /// </summary>
        internal static string Enterprise_GetByIDPermissionsNotAllowed {
            get {
                return ResourceManager.GetString("Enterprise.GetByIDPermissionsNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doanh nghiệp chưa bị xóa nên không thể khôi phục..
        /// </summary>
        internal static string Enterprise_NotDeleted {
            get {
                return ResourceManager.GetString("Enterprise.NotDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to getByHR_enterprise_attempt:{0}.
        /// </summary>
        internal static string Enterprise_RateLimitGetByHRAttempt {
            get {
                return ResourceManager.GetString("Enterprise.RateLimitGetByHRAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to getByID_enterprise_attempt:{0}.
        /// </summary>
        internal static string Enterprise_RateLimitGetByIDAttempt {
            get {
                return ResourceManager.GetString("Enterprise.RateLimitGetByIDAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to getEnterprises_enterprise_attempt:{0}.
        /// </summary>
        internal static string Enterprise_RateLimitGetEnterprisesAttempt {
            get {
                return ResourceManager.GetString("Enterprise.RateLimitGetEnterprisesAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update_enterprise_attempt:{0}.
        /// </summary>
        internal static string Enterprise_RateLimitUpdateAttempt {
            get {
                return ResourceManager.GetString("Enterprise.RateLimitUpdateAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn đã gửi request quá nhiều lần..
        /// </summary>
        internal static string Enterprise_RequestManyTimes {
            get {
                return ResourceManager.GetString("Enterprise.RequestManyTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không có quyền khôi phục doanh nghiệp này..
        /// </summary>
        internal static string Enterprise_RestorePermissionDenied {
            get {
                return ResourceManager.GetString("Enterprise.RestorePermissionDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo Epic thành công..
        /// </summary>
        internal static string Epic_CreatedSuccess {
            get {
                return ResourceManager.GetString("Epic.CreatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa Epic thành công..
        /// </summary>
        internal static string Epic_DeletedSuccess {
            get {
                return ResourceManager.GetString("Epic.DeletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật Epic thành công..
        /// </summary>
        internal static string Epic_UpdatedSuccess {
            get {
                return ResourceManager.GetString("Epic.UpdatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã thêm thành công {Count} sinh viên vào nhóm: {InternshipId}.
        /// </summary>
        internal static string InternshipGroup_LogAddedStudentsSuccess {
            get {
                return ResourceManager.GetString("InternshipGroup.LogAddedStudentsSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang thêm sinh viên vào nhóm: {InternshipId}.
        /// </summary>
        internal static string InternshipGroup_LogAddingStudents {
            get {
                return ResourceManager.GetString("InternshipGroup.LogAddingStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo nhóm thực tập thành công: {InternshipId}.
        /// </summary>
        internal static string InternshipGroup_LogCreatedSuccess {
            get {
                return ResourceManager.GetString("InternshipGroup.LogCreatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang tạo nhóm thực tập mới: {GroupName} cho kỳ: {TermId}.
        /// </summary>
        internal static string InternshipGroup_LogCreating {
            get {
                return ResourceManager.GetString("InternshipGroup.LogCreating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa nhóm thực tập thành công: {InternshipId}.
        /// </summary>
        internal static string InternshipGroup_LogDeletedSuccess {
            get {
                return ResourceManager.GetString("InternshipGroup.LogDeletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang xóa nhóm thực tập: {InternshipId}.
        /// </summary>
        internal static string InternshipGroup_LogDeleting {
            get {
                return ResourceManager.GetString("InternshipGroup.LogDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã xóa thành công sinh viên khỏi nhóm: {InternshipId}.
        /// </summary>
        internal static string InternshipGroup_LogRemovedStudentsSuccess {
            get {
                return ResourceManager.GetString("InternshipGroup.LogRemovedStudentsSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang xóa sinh viên khỏi nhóm: {InternshipId}.
        /// </summary>
        internal static string InternshipGroup_LogRemovingStudents {
            get {
                return ResourceManager.GetString("InternshipGroup.LogRemovingStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật nhóm thực tập thành công: {InternshipId}.
        /// </summary>
        internal static string InternshipGroup_LogUpdatedSuccess {
            get {
                return ResourceManager.GetString("InternshipGroup.LogUpdatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang cập nhật nhóm thực tập: {InternshipId}.
        /// </summary>
        internal static string InternshipGroup_LogUpdating {
            get {
                return ResourceManager.GetString("InternshipGroup.LogUpdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo issue thành công..
        /// </summary>
        internal static string Issue_CreateSuccess {
            get {
                return ResourceManager.GetString("Issue.CreateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa issue thành công..
        /// </summary>
        internal static string Issue_DeleteSuccess {
            get {
                return ResourceManager.GetString("Issue.DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật trạng thái issue thành công..
        /// </summary>
        internal static string Issue_UpdateStatusSuccess {
            get {
                return ResourceManager.GetString("Issue.UpdateStatusSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vị trí mới phải khác vị trí hiện tại.
        /// </summary>
        internal static string NewRoleMustBeDifferent {
            get {
                return ResourceManager.GetString("NewRoleMustBeDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page number must be greater than or equal to 1.
        /// </summary>
        internal static string PageNumber_MinValue {
            get {
                return ResourceManager.GetString("PageNumber.MinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page size must not exceed 100.
        /// </summary>
        internal static string PageSize_MaxValue {
            get {
                return ResourceManager.GetString("PageSize.MaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page size must be greater than or equal to 1.
        /// </summary>
        internal static string PageSize_MinValue {
            get {
                return ResourceManager.GetString("PageSize.MinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thông tin thành công..
        /// </summary>
        internal static string Profile_UpdateSuccess {
            get {
                return ResourceManager.GetString("Profile.UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã truy xuất thành công {Count} tài nguyên dự án.
        /// </summary>
        internal static string ProjectResources_GetAllSuccess {
            get {
                return ResourceManager.GetString("ProjectResources.GetAllSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã truy xuất thành công tài nguyên dự án: {ResourceId}.
        /// </summary>
        internal static string ProjectResources_GetByIdSuccess {
            get {
                return ResourceManager.GetString("ProjectResources.GetByIdSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project resource with ID {ResourceId} deleted successfully..
        /// </summary>
        internal static string ProjectResources_LogDeleteSuccess {
            get {
                return ResourceManager.GetString("ProjectResources.LogDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã tải tệp {FileName} lên dự án {ProjectId}.
        /// </summary>
        internal static string ProjectResources_LogUploadSuccess {
            get {
                return ResourceManager.GetString("ProjectResources.LogUploadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa dự án thành công.
        /// </summary>
        internal static string Projects_DeleteSuccess {
            get {
                return ResourceManager.GetString("Projects.DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã tạo dự án {ProjectId} cho chương trình thực tập {InternshipId}..
        /// </summary>
        internal static string Projects_LogCreateSuccess {
            get {
                return ResourceManager.GetString("Projects.LogCreateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dự án đã bị xóa {ProjectId}.
        /// </summary>
        internal static string Projects_LogDelete {
            get {
                return ResourceManager.GetString("Projects.LogDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully retrieved {Count} projects for internship ID: {InternshipId}.
        /// </summary>
        internal static string Projects_LogGetByInternshipIdSuccess {
            get {
                return ResourceManager.GetString("Projects.LogGetByInternshipIdSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dự án không tìm thấy.
        /// </summary>
        internal static string Projects_NotFound {
            get {
                return ResourceManager.GetString("Projects.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dự án đã được cập nhật {ProjectId}.
        /// </summary>
        internal static string Projects_UpdateSuccess {
            get {
                return ResourceManager.GetString("Projects.UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email thông báo không được gửi. Vui lòng thông báo trực tiếp cho người dùng..
        /// </summary>
        internal static string ResetPassword_StatusNoEmail {
            get {
                return ResourceManager.GetString("ResetPassword.StatusNoEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu đã được reset thành công nhưng email thông báo không được gửi. Vui lòng thông báo trực tiếp cho người dùng. Mật khẩu mới: {0}.
        /// </summary>
        internal static string ResetPassword_SuccessNoEmail {
            get {
                return ResourceManager.GetString("ResetPassword.SuccessNoEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu đã được reset thành công. Email thông báo đã được gửi tới {0}.
        /// </summary>
        internal static string ResetPassword_SuccessWithEmail {
            get {
                return ResourceManager.GetString("ResetPassword.SuccessWithEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role đã được thay đổi thành công nhưng email thông báo không được gửi. Vui lòng thông báo trực tiếp cho người dùng về mã nhân viên mới: {0}.
        /// </summary>
        internal static string RoleChangedButEmailFailed {
            get {
                return ResourceManager.GetString("RoleChangedButEmailFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role đã được thay đổi thành công.
        /// </summary>
        internal static string RoleChangedSuccessfully {
            get {
                return ResourceManager.GetString("RoleChangedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search term cannot exceed 200 characters.
        /// </summary>
        internal static string SearchTerm_MaxLength {
            get {
                return ResourceManager.GetString("SearchTerm.MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort column must be one of: projectname, startdate, enddate, status, createdat.
        /// </summary>
        internal static string SortColumn_AllowedValues {
            get {
                return ResourceManager.GetString("SortColumn.AllowedValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort order must be either &apos;asc&apos; or &apos;desc&apos;.
        /// </summary>
        internal static string SortOrder_AllowedValues {
            get {
                return ResourceManager.GetString("SortOrder.AllowedValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprint đã được hoàn thành thành công. {0} item đã hoàn thành, {1} item đã được di chuyển..
        /// </summary>
        internal static string Sprint_CompletedSuccess {
            get {
                return ResourceManager.GetString("Sprint.CompletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo Sprint thành công..
        /// </summary>
        internal static string Sprint_CreatedSuccess {
            get {
                return ResourceManager.GetString("Sprint.CreatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa Sprint thành công..
        /// </summary>
        internal static string Sprint_DeletedSuccess {
            get {
                return ResourceManager.GetString("Sprint.DeletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bắt đầu Sprint thành công..
        /// </summary>
        internal static string Sprint_StartedSuccess {
            get {
                return ResourceManager.GetString("Sprint.StartedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật Sprint thành công..
        /// </summary>
        internal static string Sprint_UpdatedSuccess {
            get {
                return ResourceManager.GetString("Sprint.UpdatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo stakeholder thành công..
        /// </summary>
        internal static string Stakeholder_CreateSuccess {
            get {
                return ResourceManager.GetString("Stakeholder.CreateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa stakeholder thành công..
        /// </summary>
        internal static string Stakeholder_DeleteSuccess {
            get {
                return ResourceManager.GetString("Stakeholder.DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật stakeholder thành công..
        /// </summary>
        internal static string Stakeholder_UpdateSuccess {
            get {
                return ResourceManager.GetString("Stakeholder.UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không xác định được người thực hiện thao tác..
        /// </summary>
        internal static string Users_InvalidAuditor {
            get {
                return ResourceManager.GetString("Users.InvalidAuditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản người dùng hiện tại không còn hoạt động..
        /// </summary>
        internal static string Users_NotActive {
            get {
                return ResourceManager.GetString("Users.NotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy người dùng với mã và role hiện tại..
        /// </summary>
        internal static string Users_NotFound {
            get {
                return ResourceManager.GetString("Users.NotFound", resourceCulture);
            }
        }
    }
}
