// <auto-generated />
using System;
using IOCv2.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace IOCv2.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260320020000_RewriteStudentTerms")]
    partial class RewriteStudentTerms
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Model snapshot is managed by AppDbContextModelSnapshot.cs
        }
    }
}
