// <auto-generated />
using System;
using IOCv2.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IOCv2.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IOCv2.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("log_id");

                    b.Property<short>("Action")
                        .HasColumnType("smallint")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("entity_type");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<Guid>("PerformedById")
                        .HasColumnType("uuid")
                        .HasColumnName("performed_by");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("AuditLogId")
                        .HasName("pk_audit_logs");

                    b.HasIndex("PerformedById")
                        .HasDatabaseName("ix_audit_logs_performed_by_id");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_audit_logs_entity_type_entity_id");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("IOCv2.Domain.Entities.Enterprise", b =>
                {
                    b.Property<Guid>("EnterpriseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("enterprise_id");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<string>("BackgroundUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("background_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Industry")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("industry");

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_verified");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("logo_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<short>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("status");

                    b.Property<string>("TaxCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tax_code");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<string>("Website")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("website");

                    b.HasKey("EnterpriseId")
                        .HasName("pk_enterprises");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_enterprises_name");

                    b.HasIndex("TaxCode")
                        .IsUnique()
                        .HasDatabaseName("ix_enterprises_tax_code");

                    b.ToTable("enterprises", (string)null);
                });

            modelBuilder.Entity("IOCv2.Domain.Entities.EnterpriseUser", b =>
                {
                    b.Property<Guid>("EnterpriseUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("enterprise_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("EnterpriseId")
                        .HasColumnType("uuid")
                        .HasColumnName("enterprise_id");

                    b.Property<string>("Position")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("position");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("EnterpriseUserId")
                        .HasName("pk_enterprise_users");

                    b.HasIndex("EnterpriseId")
                        .HasDatabaseName("ix_enterprise_users_enterprise_id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_enterprise_users_user_id");

                    b.ToTable("enterprise_users", (string)null);
                });

            modelBuilder.Entity("IOCv2.Domain.Entities.InternshipGroup", b =>
                {
                    b.Property<Guid>("InternshipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("internship_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<Guid?>("EnterpriseId")
                        .HasColumnType("uuid")
                        .HasColumnName("enterprise_id");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("group_name");

                    b.Property<Guid?>("MentorId")
                        .HasColumnType("uuid")
                        .HasColumnName("mentor_id");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<Guid>("TermId")
                        .HasColumnType("uuid")
                        .HasColumnName("term_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("InternshipId")
                        .HasName("pk_internship_groups");

                    b.HasIndex("EnterpriseId")
                        .HasDatabaseName("ix_internship_groups_enterprise_id");

                    b.HasIndex("MentorId")
                        .HasDatabaseName("ix_internship_groups_mentor_id");

                    b.ToTable("internship_groups", (string)null);
                });

            modelBuilder.Entity("IOCv2.Domain.Entities.InternshipStudent", b =>
                {
                    b.Property<Guid>("InternshipId")
                        .HasColumnType("uuid")
                        .HasColumnName("internship_id");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<short>("Role")
                        .HasColumnType("smallint")
                        .HasColumnName("role");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("InternshipId", "StudentId")
                        .HasName("pk_internship_students");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_internship_students_student_id");

                    b.ToTable("internship_students", (string)null);
                });

            modelBuilder.Entity("IOCv2.Domain.Entities.PasswordResetToken", b =>
            modelBuilder.Entity("IOCv2.Domain.Entities.InternshipApplication", b =>
                {
                    b.Property<Guid>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<DateTime>("AppliedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("applied_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("InternshipId")
                        .HasColumnType("uuid")
                        .HasColumnName("internship_id");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid?>("ReviewedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by");

                    b.Property<Guid?>("ReviewerEnterpriseUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewer_enterprise_user_id");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("ApplicationId")
                        .HasName("pk_internship_applications");

                    b.HasIndex("ReviewerEnterpriseUserId")
                        .HasDatabaseName("ix_internship_applications_reviewer_enterprise_user_id");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_internship_applications_student_id");

                    b.HasIndex("InternshipId", "StudentId")
                        .IsUnique()
                        .HasDatabaseName("ix_internship_applications_internship_id_student_id");

                    b.ToTable("internship_applications", (string)null);
                });

            modelBuilder.Entity("IOCv2.Domain.Entities.InternshipGroup", b =>
                {
                    b.Property<Guid>("InternshipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("internship_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<Guid?>("EnterpriseId")
                        .HasColumnType("uuid")
                        .HasColumnName("enterprise_id");

                    b.Property<Guid>("MentorId")
                        .HasColumnType("uuid")
                        .HasColumnName("mentor_id");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<Guid>("TermId")
                        .HasColumnType("uuid")
                        .HasColumnName("term_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("InternshipId")
                        .HasName("pk_internship_groups");

                    b.HasIndex("EnterpriseId")
                        .HasDatabaseName("ix_internship_groups_enterprise_id");

                    b.HasIndex("InternshipId")
                        .HasDatabaseName("ix_internship_groups_internship_id");

                    b.HasIndex("MentorId")
                        .HasDatabaseName("ix_internship_groups_mentor_id");

                    b.HasIndex("TermId")
                        .HasDatabaseName("ix_internship_groups_term_id");

                    b.ToTable("internship_groups", (string)null);
                });

            modelBuilder.Entity("IOCv2.Domain.Entities.InternshipStudents", b =>
                {
                    b.Property<Guid>("InternshipId")
                        .HasColumnType("uuid")
                        .HasColumnName("internship_id");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("joined_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_at");

                    b.Property<short>("Role")
                        .HasColumnType("smallint")
                        .HasColumnName("role");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("InternshipId", "StudentId")
                        .HasName("pk_internship_students");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_internship_students_student_id");

                    b.ToTable("internship_students", (string)null);
                });

            modelBuilder.Entity("IOCv2.Domain.Entities.Logbook", b =>
                {
                    b.Property<Guid>("LogbookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("logbook_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DateReport")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_report");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("InternshipId")
                        .HasColumnType("uuid")
                        .HasColumnName("internship_id");

                    b.Property<string>("Issue")
                        .HasColumnType("text")
                        .HasColumnName("issue");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("plan");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<Guid?>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("LogbookId")
                        .HasName("pk_logbooks");

                    b.HasIndex("InternshipId")
                        .HasDatabaseName("ix_logbooks_internship_id");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_logbooks_student_id");

                    b.ToTable("logbooks", (string)null);
                });

            modelBuilder.Entity("IOCv2.Domain.Entities.PasswordResetToken", b =>
                {
                    b.Property<Guid>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("token_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("TokenId")
                        .HasName("pk_password_reset_tokens");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_password_reset_tokens_expires_at");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_password_reset_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_password_reset_tokens_user_id");

                    b.ToTable("password_reset_tokens", (string)null);
                });

            modelBuilder.Entity("IOCv2.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("project_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<Guid?>("InternshipGroupInternshipId")
                        .HasColumnType("uuid")
                        .HasColumnName("internship_group_internship_id");

                    b.Property<Guid>("InternshipId")
                        .HasColumnType("uuid")
                        .HasColumnName("internship_id");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("project_name");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<short?>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("ProjectId")
                        .HasName("pk_projects");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_projects_created_at");

                    b.HasIndex("InternshipGroupInternshipId")
                        .HasDatabaseName("ix_projects_internship_group_internship_id");

                    b.HasIndex("InternshipId")
                        .HasDatabaseName("ix_projects_internship_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_projects_status");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("IOCv2.Domain.Entities.ProjectResources", b =>
                {
                    b.Property<Guid>("ProjectResourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("project_resource_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("ResourceName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("resource_name");

                    b.Property<short>("ResourceType")
                        .HasColumnType("smallint")
                        .HasColumnName("resource_type");

                    b.Property<string>("ResourceUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("resource_url");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("ProjectResourceId")
                        .HasName("pk_project_resources");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_project_resources_created_at");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_project_resources_project_id");

                    b.HasIndex("ResourceType")
                        .HasDatabaseName("ix_project_resources_resource_type");

                    b.ToTable("project_resources", (string)null);
                });

            modelBuilder.Entity("IOCv2.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("RefreshTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_revoked");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("token");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("RefreshTokenId")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("IOCv2.Domain.Entities.Sprint", b =>
                {
                    b.Property<Guid>("SprintId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("sprint_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("Goal")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("goal");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("SprintId")
                        .HasName("pk_sprints");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_sprints_project_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_sprints_status");

                    b.ToTable("sprints", (string)null);
                });

            modelBuilder.Entity("IOCv2.Domain.Entities.SprintWorkItem", b =>
                {
                    b.Property<Guid>("SprintId")
                        .HasColumnType("uuid")
                        .HasColumnName("sprint_id");

                    b.Property<Guid>("WorkItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_item_id");

                    b.Property<float>("BoardOrder")
                        .HasColumnType("real")
                        .HasColumnName("board_order");

                    b.HasKey("SprintId", "WorkItemId")
                        .HasName("pk_sprint_work_items");

                    b.HasIndex("WorkItemId")
                        .HasDatabaseName("ix_sprint_work_items_work_item_id");

                    b.HasIndex("SprintId", "BoardOrder")
                        .HasDatabaseName("ix_sprint_work_items_board_order");

                    b.ToTable("sprint_work_items", (string)null);
                });

            modelBuilder.Entity("IOCv2.Domain.Entities.Stakeholder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("phone_number");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Role")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("role");

                    b.Property<short>("Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_stakeholders");

                    b.HasIndex("Email")
                        .HasDatabaseName("ix_stakeholders_email");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_stakeholders_project_id");

                    b.HasIndex("ProjectId", "Email")
                        .IsUnique()
                        .HasDatabaseName("ix_stakeholders_project_email_unique")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("stakeholders", (string)null);
                });

            modelBuilder.Entity("IOCv2.Domain.Entities.StakeholderIssue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<Guid>("StakeholderId")
                        .HasColumnType("uuid")
                        .HasColumnName("stakeholder_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_stakeholder_issues");

                    b.HasIndex("StakeholderId")
                        .HasDatabaseName("ix_stakeholder_issues_stakeholder_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_stakeholder_issues_status");

                    b.ToTable("stakeholder_issues", (string)null);
                });

            modelBuilder.Entity("IOCv2.Domain.Entities.Student", b =>
                {
                    b.Property<Guid>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<string>("ClassName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("class_name");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_at");

                    b.Property<decimal?>("Gpa")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("gpa");

                    b.Property<string>("HighestDegree")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("highest_degree");

                    b.Property<short>("InternshipStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("internship_status");

                    b.Property<string>("Major")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("major");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("StudentId")
                        .HasName("pk_students");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_students_user_id");

                    b.ToTable("students", (string)null);
                });

            modelBuilder.Entity("IOCv2.Domain.Entities.StudentTerm", b =>
                {
                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<Guid>("TermId")
                        .HasColumnType("uuid")
                        .HasColumnName("term_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_at");

                    b.Property<short?>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("StudentId", "TermId")
                        .HasName("pk_student_terms");

                    b.HasIndex("TermId")
                        .HasDatabaseName("ix_student_terms_term_id");

                    b.ToTable("student_terms", (string)null);
                });

            modelBuilder.Entity("IOCv2.Domain.Entities.Term", b =>
                {
                    b.Property<Guid>("TermId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("term_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<Guid>("UniversityId")
                        .HasColumnType("uuid")
                        .HasColumnName("university_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("TermId")
                        .HasName("pk_terms");

                    b.HasIndex("UniversityId")
                        .HasDatabaseName("ix_terms_university_id");

                    b.ToTable("terms", (string)null);
                });

            modelBuilder.Entity("IOCv2.Domain.Entities.University", b =>
                {
                    b.Property<Guid>("UniversityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uni_id");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("logo_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<short>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("UniversityId")
                        .HasName("pk_universities");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_universities_code");

                    b.ToTable("universities", (string)null);
                });

            modelBuilder.Entity("IOCv2.Domain.Entities.UniversityUser", b =>
                {
                    b.Property<Guid>("UniversityUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uni_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("UniversityId")
                        .HasColumnType("uuid")
                        .HasColumnName("uni_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("UniversityUserId")
                        .HasName("pk_university_users");

                    b.HasIndex("UniversityId")
                        .HasDatabaseName("ix_university_users_university_id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_university_users_user_id");

                    b.ToTable("university_users", (string)null);
                });

            modelBuilder.Entity("IOCv2.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("full_name");

                    b.Property<short>("Gender")
                        .HasColumnType("smallint")
                        .HasColumnName("gender");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("phone_number");

                    b.Property<short>("Role")
                        .HasColumnType("smallint")
                        .HasColumnName("role");

                    b.Property<short>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<string>("UserCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("user_code");

                    b.HasKey("UserId")
                        .HasName("pk_users");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_users_created_at");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_users_phone_number");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_users_status")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("UserCode")
                        .IsUnique()
                        .HasDatabaseName("ix_users_user_code");

                    b.HasIndex("Role", "Status")
                        .HasDatabaseName("ix_users_role_status");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("IOCv2.Domain.Entities.UserCodeSequence", b =>
                {
                    b.Property<short>("Role")
                        .HasColumnType("smallint")
                        .HasColumnName("role");

                    b.Property<int>("CurrentNumber")
                        .HasColumnType("integer")
                        .HasColumnName("current_number");

                    b.HasKey("Role")
                        .HasName("pk_user_code_sequences");

                    b.ToTable("user_code_sequences", (string)null);
                });

            modelBuilder.Entity("IOCv2.Domain.Entities.WorkItem", b =>
                {
                    b.Property<Guid>("WorkItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("work_item_id");

                    b.Property<Guid?>("AssigneeId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignee_id");

                    b.Property<float>("BacklogOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasDefaultValue(0f)
                        .HasColumnName("backlog_order");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<short?>("Priority")
                        .HasColumnType("smallint")
                        .HasColumnName("priority");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<short?>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<int?>("StoryPoint")
                        .HasColumnType("integer")
                        .HasColumnName("story_point");

                    b.Property<Guid?>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<short>("Type")
                        .HasColumnType("smallint")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("WorkItemId")
                        .HasName("pk_work_items");

                    b.HasIndex("AssigneeId")
                        .HasDatabaseName("ix_work_items_assignee_id");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_work_items_parent_id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_work_items_project_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_work_items_status");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_work_items_student_id");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_work_items_type");

                    b.ToTable("work_items", (string)null);
                });

            modelBuilder.Entity("LogbookWorkItem", b =>
                {
                    b.Property<Guid>("LogbookId")
                        .HasColumnType("uuid")
                        .HasColumnName("logbook_id");

                    b.Property<Guid>("WorkItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_item_id");

                    b.HasKey("LogbookId", "WorkItemId")
                        .HasName("pk_logbook_work_items");

                    b.HasIndex("WorkItemId")
                        .HasDatabaseName("ix_logbook_work_items_work_item_id");

                    b.ToTable("logbook_work_items", (string)null);
                });

            modelBuilder.Entity("IOCv2.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("IOCv2.Domain.Entities.User", "PerformedBy")
                        .WithMany("PerformedLogs")
                        .HasForeignKey("PerformedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_audit_logs_users_performed_by_id");

                    b.Navigation("PerformedBy");
                });

            modelBuilder.Entity("IOCv2.Domain.Entities.EnterpriseUser", b =>
                {
                    b.HasOne("IOCv2.Domain.Entities.Enterprise", "Enterprise")
                        .WithMany("EnterpriseUsers")
                        .HasForeignKey("EnterpriseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_enterprise_users_enterprises_enterprise_id");

                    b.HasOne("IOCv2.Domain.Entities.User", "User")
                        .WithOne("EnterpriseUser")
                        .HasForeignKey("IOCv2.Domain.Entities.EnterpriseUser", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_enterprise_users_users_user_id");

                    b.Navigation("Enterprise");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IOCv2.Domain.Entities.InternshipApplication", b =>
                {
                    b.HasOne("IOCv2.Domain.Entities.InternshipGroup", "InternshipGroup")
                        .WithMany("InternshipApplications")
                        .HasForeignKey("InternshipId")
                        .HasConstraintName("fk_internship_applications_internship_groups_internship_id");

                    b.HasOne("IOCv2.Domain.Entities.EnterpriseUser", "Reviewer")
                        .WithMany("ReviewedApplications")
                        .HasForeignKey("ReviewerEnterpriseUserId")
                        .HasConstraintName("fk_internship_applications_enterprise_users_reviewer_enterpris");

                    b.HasOne("IOCv2.Domain.Entities.Student", "Student")
                        .WithMany("InternshipApplications")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("fk_internship_applications_students_student_id");

                    b.Navigation("InternshipGroup");

                    b.Navigation("Reviewer");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("IOCv2.Domain.Entities.InternshipGroup", b =>
                {
                    b.HasOne("IOCv2.Domain.Entities.Enterprise", "Enterprise")
                        .WithMany("InternshipGroups")
                        .HasForeignKey("EnterpriseId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_internship_groups_enterprises_enterprise_id");

                    b.HasOne("IOCv2.Domain.Entities.EnterpriseUser", "Mentor")
                        .WithMany("MentoringGroups")
                        .HasForeignKey("MentorId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_internship_groups_enterprise_users_mentor_id");

                    b.Navigation("Enterprise");

                    b.Navigation("Mentor");
                });

            modelBuilder.Entity("IOCv2.Domain.Entities.InternshipStudent", b =>
                {
                    b.HasOne("IOCv2.Domain.Entities.InternshipGroup", "InternshipGroup")
                        .WithMany("Members")
                        .HasForeignKey("InternshipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_internship_students_internship_groups_internship_id");

                    b.HasOne("IOCv2.Domain.Entities.Student", "Student")
                        .WithMany("InternshipStudents")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_internship_students_students_student_id");
                        .WithMany("MentoredGroups")
                        .HasForeignKey("MentorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_internship_groups_enterprise_users_mentor_id");

                    b.HasOne("IOCv2.Domain.Entities.Term", "Term")
                        .WithMany("InternshipGroups")
                        .HasForeignKey("TermId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_internship_groups_terms_term_id");

                    b.Navigation("Enterprise");

                    b.Navigation("Mentor");

                    b.Navigation("Term");
                });

            modelBuilder.Entity("IOCv2.Domain.Entities.InternshipStudents", b =>
                {
                    b.HasOne("IOCv2.Domain.Entities.InternshipGroup", "InternshipGroup")
                        .WithMany("InternshipStudents")
                        .HasForeignKey("InternshipId")
                        .HasConstraintName("fk_internship_students_internship_groups_internship_id");

                    b.HasOne("IOCv2.Domain.Entities.Student", "Student")
                        .WithMany("InternshipGroups")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("fk_internship_students_students_student_id");

                    b.Navigation("InternshipGroup");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("IOCv2.Domain.Entities.Logbook", b =>
                {
                    b.HasOne("IOCv2.Domain.Entities.InternshipGroup", "InternshipGroup")
                        .WithMany("Logbooks")
                        .HasForeignKey("InternshipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_logbooks_internship_groups_internship_id");

                    b.HasOne("IOCv2.Domain.Entities.Student", "Student")
                        .WithMany("Logbooks")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("fk_logbooks_students_student_id");

                    b.Navigation("InternshipGroup");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("IOCv2.Domain.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("IOCv2.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_password_reset_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IOCv2.Domain.Entities.Project", b =>
                {
                    b.HasOne("IOCv2.Domain.Entities.InternshipGroup", null)
                        .WithMany("Projects")
                        .HasForeignKey("InternshipGroupInternshipId")
                        .HasConstraintName("fk_projects_internship_groups_internship_group_internship_id");

                    b.HasOne("IOCv2.Domain.Entities.InternshipGroup", "InternshipGroup")
                        .WithMany()
                        .HasForeignKey("InternshipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_projects_internship_groups_internship_id");

                    b.Navigation("InternshipGroup");
                });

            modelBuilder.Entity("IOCv2.Domain.Entities.ProjectResources", b =>
                {
                    b.HasOne("IOCv2.Domain.Entities.Project", "Project")
                        .WithMany("ProjectResources")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_resources_projects_project_id");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("IOCv2.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("IOCv2.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IOCv2.Domain.Entities.Sprint", b =>
                {
                    b.HasOne("IOCv2.Domain.Entities.Project", null)
                        .WithMany("Sprints")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sprints_projects_project_id");
                });

            modelBuilder.Entity("IOCv2.Domain.Entities.SprintWorkItem", b =>
                {
                    b.HasOne("IOCv2.Domain.Entities.Sprint", "Sprint")
                        .WithMany("SprintWorkItems")
                        .HasForeignKey("SprintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_sprint_work_items_sprints_sprint_id");

                    b.HasOne("IOCv2.Domain.Entities.WorkItem", "WorkItem")
                        .WithMany()
                        .HasForeignKey("WorkItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sprint_work_items_work_items_work_item_id");

                    b.Navigation("Sprint");

                    b.Navigation("WorkItem");
                });

            modelBuilder.Entity("IOCv2.Domain.Entities.Stakeholder", b =>
                {
                    b.HasOne("IOCv2.Domain.Entities.Project", "Project")
                        .WithMany("Stakeholders")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stakeholders_projects");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("IOCv2.Domain.Entities.StakeholderIssue", b =>
                {
                    b.HasOne("IOCv2.Domain.Entities.Stakeholder", "Stakeholder")
                        .WithMany("Issues")
                        .HasForeignKey("StakeholderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_stakeholder_issues_stakeholders");

                    b.Navigation("Stakeholder");
                });

            modelBuilder.Entity("IOCv2.Domain.Entities.Student", b =>
                {
                    b.HasOne("IOCv2.Domain.Entities.User", "User")
                        .WithOne("Student")
                        .HasForeignKey("IOCv2.Domain.Entities.Student", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_students_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IOCv2.Domain.Entities.StudentTerm", b =>
                {
                    b.HasOne("IOCv2.Domain.Entities.Student", "Student")
                        .WithMany("StudentTerms")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_student_terms_students_student_id");

                    b.HasOne("IOCv2.Domain.Entities.Term", "Term")
                        .WithMany("StudentTerms")
                        .HasForeignKey("TermId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_student_terms_terms_term_id");

                    b.Navigation("Student");

                    b.Navigation("Term");
                });

            modelBuilder.Entity("IOCv2.Domain.Entities.Term", b =>
                {
                    b.HasOne("IOCv2.Domain.Entities.University", "University")
                        .WithMany("Terms")
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_terms_universities_university_id");

                    b.Navigation("University");
                });

            modelBuilder.Entity("IOCv2.Domain.Entities.UniversityUser", b =>
                {
                    b.HasOne("IOCv2.Domain.Entities.University", "University")
                        .WithMany("UniversityUsers")
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_university_users_universities_university_id");

                    b.HasOne("IOCv2.Domain.Entities.User", "User")
                        .WithOne("UniversityUser")
                        .HasForeignKey("IOCv2.Domain.Entities.UniversityUser", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_university_users_users_user_id");

                    b.Navigation("University");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IOCv2.Domain.Entities.WorkItem", b =>
                {
                    b.HasOne("IOCv2.Domain.Entities.Student", "Assignee")
                        .WithMany()
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_work_items_students_assignee_id");

                    b.HasOne("IOCv2.Domain.Entities.WorkItem", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_work_items_work_items_parent_id");

                    b.HasOne("IOCv2.Domain.Entities.Project", null)
                        .WithMany("WorkItems")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_work_items_projects_project_id");

                    b.HasOne("IOCv2.Domain.Entities.Student", null)
                        .WithMany("WorkItems")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("fk_work_items_students_student_id");

                    b.Navigation("Assignee");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("LogbookWorkItem", b =>
                {
                    b.HasOne("IOCv2.Domain.Entities.Logbook", null)
                        .WithMany()
                        .HasForeignKey("LogbookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_logbook_work_items_logbooks_logbook_id");

                    b.HasOne("IOCv2.Domain.Entities.WorkItem", null)
                        .WithMany()
                        .HasForeignKey("WorkItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_logbook_work_items_work_items_work_item_id");
                });

            modelBuilder.Entity("IOCv2.Domain.Entities.Enterprise", b =>
                {
                    b.Navigation("EnterpriseUsers");

                    b.Navigation("InternshipGroups");
                });

            modelBuilder.Entity("IOCv2.Domain.Entities.EnterpriseUser", b =>
                {
                    b.Navigation("MentoringGroups");
                    b.Navigation("MentoredGroups");

                    b.Navigation("ReviewedApplications");
                });

            modelBuilder.Entity("IOCv2.Domain.Entities.InternshipGroup", b =>
                {
                    b.Navigation("Members");
                    b.Navigation("InternshipApplications");

                    b.Navigation("InternshipStudents");

                    b.Navigation("Logbooks");

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("IOCv2.Domain.Entities.Project", b =>
                {
                    b.Navigation("ProjectResources");

                    b.Navigation("Sprints");

                    b.Navigation("Stakeholders");

                    b.Navigation("WorkItems");
                });

            modelBuilder.Entity("IOCv2.Domain.Entities.Sprint", b =>
                {
                    b.Navigation("SprintWorkItems");
                });

            modelBuilder.Entity("IOCv2.Domain.Entities.Stakeholder", b =>
                {
                    b.Navigation("Issues");
                });

            modelBuilder.Entity("IOCv2.Domain.Entities.Student", b =>
                {
                    b.Navigation("InternshipStudents");
                    b.Navigation("InternshipApplications");

                    b.Navigation("InternshipGroups");

                    b.Navigation("Logbooks");

                    b.Navigation("StudentTerms");

                    b.Navigation("WorkItems");
                });

            modelBuilder.Entity("IOCv2.Domain.Entities.Term", b =>
                {
                    b.Navigation("InternshipGroups");

                    b.Navigation("StudentTerms");
                });

            modelBuilder.Entity("IOCv2.Domain.Entities.University", b =>
                {
                    b.Navigation("Terms");

                    b.Navigation("UniversityUsers");
                });

            modelBuilder.Entity("IOCv2.Domain.Entities.User", b =>
                {
                    b.Navigation("EnterpriseUser");

                    b.Navigation("PerformedLogs");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Student");

                    b.Navigation("UniversityUser");
                });

            modelBuilder.Entity("IOCv2.Domain.Entities.WorkItem", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
